import '../js/bootstrap'
import '../js/jquery.isotope'
import '../js/owl.carousel'
import '../js/SmoothScroll'
import '../js/main'
import '../css/animate.css'
import '../css/bootstrap.min.css'
import '../css/owl.carousel.css'
import '../css/owl.theme.css'
import '../css/responsive.css'
import '../css/style.css'
import '../index.html'
// import '../fonts/fonts/glyphicons-halflings-regular.eot'
// import '../fonts/fonts/glyphicons-halflings-regular.svg'
// import '../fonts/fonts/glyphicons-halflings-regular.ttf'
// import '../fonts/fonts/glyphicons-halflings-regular.woff'
// import '../fonts/fonts/glyphicons-halflings-regular.woff2'